sudo: required
services:
  - docker

before_install:
  - docker build -t viswanis/docker-react -f Dockerfile.dev .

script:
  #- docker run viswanis/docker-react npm run test -- --coverage
  - docker run -e CI=true viswanis/docker-react npm run test
